---
title: "tidymodels_try"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidymodels)
```

```{r}
iris_split <- initial_split(iris, prop = 0.6)
iris_split
```
```{r}
iris_split %>% 
  testing() %>% 
  glimpse()
```
```{r}
iris_recipe <- iris_split %>% 
  training() %>% 
  recipe(Species ~ .) %>% 
  step_corr(all_predictors()) %>% 
  step_center(all_predictors(), -all_outcomes()) %>%  # why need to exclude outcomes explicitly?
  step_scale(all_predictors(), -all_outcomes()) %>% 
  prep()
iris_recipe
```

```{r}
iris_recipe2 <- iris_split %>% 
  training() %>% 
  recipe(Species ~ .) %>% 
  step_corr(all_predictors()) %>% 
  step_center(all_predictors()) %>%  # why need to exclude outcomes explicitly?
  step_scale(all_predictors()) %>% 
  prep()
iris_recipe2
```
```{r}
iris_recipe %>% 
  bake(testing(iris_split))
```
```{r}
iris_testing <- iris_recipe2 %>% 
  bake(testing(iris_split))
iris_training <- juice(iris_recipe2)
```

```{r}
iris_ranger <- rand_forest(trees = 100, mode = "classification") %>% 
  set_engine("ranger") %>% 
  fit(Species ~ ., data = iris_training)

iris_ranger
```
```{r}
iris_rf <- rand_forest(trees = 100, mode = "classification") %>% 
  set_engine("randomForest") %>% 
  fit(Species ~ ., data = iris_training)

iris_rf
```

```{r}
iris_ranger %>% 
  predict(iris_testing) %>% 
  bind_cols(iris_testing) %>% 
  glimpse()
```

```{r}
iris_ranger %>% 
  predict(iris_testing) %>% 
  bind_cols(iris_testing) %>% 
  metrics(truth = Species, estimate = .pred_class)
```

```{r}

iris_rf %>% 
  predict(iris_testing) %>% 
  bind_cols(iris_testing) %>% 
  metrics(truth = Species, estimate = .pred_class)
```
```{r}
iris_probs <- iris_ranger %>% 
  predict(iris_testing, type = "prob") %>% 
  bind_cols(iris_testing) 
  # glimpse()
```

```{r}

iris_probs %>% 
  gain_curve(Species, .pred_setosa:.pred_virginica) %>% 
  autoplot()
```
```{r}

iris_probs %>% 
  roc_curve(Species, .pred_setosa:.pred_virginica) %>% 
  autoplot()
```
```{r}
predict(iris_ranger, iris_testing, type = "prob") %>% 
  bind_cols(predict(iris_ranger, iris_testing)) %>% 
  bind_cols(select(iris_testing, Species)) %>% 
  metrics(Species, .pred_setosa:.pred_virginica, estimate = .pred_class)
```

